### PR TITLE
feat(README.md): add install method for nix users

### PR DESCRIPTION
**Pull request by ryoppippi**
Hello!
This plugin is really fun and works perfect! Thanks.
I added an installing description for NixOS user!

### CODE REVIEW

**Comment by vyfor** [comment]
Hey, appreciate the contribution but I don't think this is necessary. Does it only work on NixOS if you use the `nix develop` command?

**Comment by ryoppippi** [comment]
No, but it is great because I don't install rust globally.
This instruction is similar to this plugin https://github.com/eraserhd/parinfer-rust#vim-plug

As you use nix in this repository, this is good instruction I think

**Comment by vyfor** [comment]
I believe Nix support was introduced in #96 - doesn't that already cover setting up Rust in the project? I haven't used NixOS myself, so I'm unsure if it's indeed a good approach. I'd rather not to add extra stuff to the README unless absolutely necessary.
Not everyone uses Nix or even Linux, so it seems a bit excess to include those steps for every installation option, which I plan to extend in the near future.

**Comment by ryoppippi** [comment]
It's your OSS, so you don't like it close it.

**Comment by ryoppippi** [comment]
It's your OSS.
If you don't like this PR, I don't care, just close it.
I'm so sorry that I send a PR which is not following your preference.

**Pull request closed without merging**
