### PR TITLE
feat: use image from user client id when specified

### PR DESCRIPTION
**Pull request by cpea2506**
This PR allows user to fetch image from their custom Discord client's id instead of fetching only from this repo's asset folder.

## How has this been tested:
Tested with my own client id

```lua
require('cord').setup({
  editor = {
    image = "neovim",
    client = "914799712794705961",
  },
})
```

### Presence showcase:

Screenshot 2024-04-21 at 21 25 29

Screenshot 2024-04-21 at 21 26 00

### CODE REVIEW

**Comment by vyfor** [comment]
Good idea! But I was considering to introduce a new field to the configuration as follows:
```lua
require('cord').setup({
  icons = {
    lua = 'lua',
    rust = 'https://example.com/rust.png',
  },
})
```
This will override the default file assets, and allow them to be fetched directly from the custom application instead.
The other two commits look good to me.

What do you think?

**Comment by cpea2506** [comment]
Yes, that's a great idea. It can be used to expand the ability for user customization. So, what's the next step in your thinking?

**Comment by vyfor** [comment]
I have a basic idea of how I'm going to implement it. I'll start working on it right away.
Regarding the other changes, I believe the renaming makes the file names unnecessarily long, how about we leave them as is? And thanks for noticing the macro I forgot to remove!

**Comment by vyfor** [comment]
I'll be closing this PR for the time being.

**Comment by cpea2506** [comment]
The naming is changed to make it work with data fetching from discord application, since discord rich presence data is not folder-based. If you can do something to improve it, the name can be reserved as is. 😊

**Comment by vyfor** [comment]
Hey there @cpea2506. I'm almost finished with the implementation (tracked in #31). You can give it a try by switching to the `dev` branch instead. If you have any ideas in mind, contributions are very welcome!

**Pull request closed without merging**
